### ISSUE TITLE
Issue with Multiple Controllers with Different Signalr Dependencies

### ISSUE THREAD

**Issue by barefootdeveloper** [JustMaier/angular-signalr-hub#11]
I'm having an issue where signalr client side events are not being triggered when the server fires them.

I've tracked the problem down to using different hubs on different controllers.

Whatever hubs are active on my first page load those hubs will work perfectly.  Any hubs that are subsequently setup by new controllers will not receive their client side events called from the server.

I believe this is because the client code determines which hubs to connect to on the server and because there are no client events subscribed to for the inactive hubs it never initializes the connection for those inactive hubs. [See note listed here: http://www.asp.net/signalr/overview/signalr-20/hubs-api/hubs-api-guide-javascript-client#establishconnection]

Then when the controllers become active, and the client events are subscribed to, the connection is never re-established because the globalConnection variable has already been given a value.

I've confirmed this is the problem by commenting out the conditional around initGlobalConnection(options).  Whenever this method fires every time a hub is created the client side events are always properly triggered by the server.  This of course isn't a suitable long term fix, but it did prove out the theory.

I think the long-term solution to this is probably to reset the global connection whenever the active hubs on the client change.  I'll probably explore this, but I figured I'd post this to open a dialog in case I was missing something obvious.

Example:

PageOneController 
    uses HubA
       Has Client Side Event ReceivedGreeting

PageTwoController
    uses HubB
        Has Client Side Event UpdateTicker

If PageOneController is the initial controller hit, ReceivedGreeting client event fires properly and UpdateTicker client event does not.

If PageTwoController is the initial controller, UpdateTicker client event fires properly and ReceivedGreeting client event does not fire properly.

**Comment by mcianc** [comment]
Me too had the same problem solved with 
useSharedConnection: false

**Comment by pafrench** [comment]
So I've put in the interim fix as suggested by @mcianc above. My problem is, I was using the shared connection to display the state of the connection to the user (green wifi icon for connected, etc).

Obviously I can't do this when there isn't a single, shared connection (with multiple hubs) - is there an update on a fix for this issue?
