### ISSUE TITLE
Issue with multiple open proxies being created and not cleaned up

### ISSUE THREAD

**Issue by mleyb** [JustMaier/angular-signalr-hub#14]
I'm using Typescript. Controller is created on each navigate to one of my pages. I create a new "Hub" inside my controller constructor. When I navigate away from the page, scope & controller are removed, but the "Hub" is never cleaned up and - through usage of my app for a while - I end up with many, many open hub proxies, with no way to clean them up.

Is this an issue, or is there a way to clean up a hub proxy when it's no longer in "scope"/used? (whilst still leaving the underlying connection open)

**Comment by ronaldbluethl** [comment]
are there any updates regarding this issue?

**Comment by DeBiese** [comment]
@ronaldbluethl 
Have you tried putting your hub instance in a service (that you inject in your controller) instead of a controller as per @JustMaier 's suggestion? That's how he originally intended it to be used...

**Comment by mleyb** [comment]
^ this is what worked for me in the end

**Comment by ronaldbluethl** [comment]
@DeBiese @mleyb Thanks four your replies. I finally got it working by removing the variable globalConnections and always returning a new connection instead of using a shared one in getConnection()

This is what works for me at the moment. Do you see any problem here? Is the approach putting the hub instance in a service maybe the better one?

```javascript
var globalConnections = [];

function getConnection(options) {
			return initNewConnection(options);
		}

**Comment by DeBiese** [comment]
@ronaldbluethl If you don't want to use the globalConnections, you should just add useSharedConnections equal to false to your options. It will result in getConnection returning the output of initNewConnection... No need to change the getConnection function for that.

Still, I would put the hub in a service...

**Comment by ronaldbluethl** [comment]
@DeBiese You're right. I totally overlooked that. Nevertheless, I do not really get the approach with the service. What is the big advantage of moving the hub into a service? Do you mean using @JustMaier's 'Hub' factory as a service? Thanks for the clarification.

**Comment by DeBiese** [comment]
I mean using a service as a wrapper around your hub. You create the hub in your service and expose methods/functions on the service that can invoke methods/functions on your hub.
The advantage of using the service approach is that you open only one hub proxy and that one hub can be used across all your controllers.

Take a look at the demo applications mentioned in the readme.
In the EmployeeGrid application look for the EmployeeGrid.js file. In the simplechat demo look for ChatService.js as an example.

**Comment by ronaldbluethl** [comment]
Alright, now I got it. I was already using the described method. I misunderstood 'service' in this context, because the wrapper is actually an angular factory, not a service. Thanks for your help, really appreciated.
