### ISSUE TITLE
How to use OAuth Bearer token with this wrapper library

### ISSUE THREAD

**Issue by mahichr** [JustMaier/angular-signalr-hub#22]
Hi,
I'm using OAuth in my angular web appliction. How can I send my oauth bearer token when making signalR hub calls so that all my requests are authenticated?

**Comment by ersingencturk** [comment]
you can use query string:

_hub = new Hub('ChatHub', {
			listeners: { //Client methods
				'broadcastMessage': function(from, message) {
				
				}
			},
			methods: ['DoSomthing'],
			rootPath: appSettingsProvider.apiUrl + '/signalrurl',
			queryParams: {
				'token': accessToken <-- Your oauth token (your provider should be configured to read from query string.
			},
			//handle connection error
			errorHandler: function(error) {
				//console.error(error);
			},
			logging: false
		});

**Comment by JustMaier** [comment]
Did something similar to @ersingencturk and I can confirm that it works.
