### ISSUE TITLE
jsonp

### ISSUE THREAD

**Issue by gsales** [JustMaier/angular-signalr-hub#26]
Hi!

how i do requests which using jsonp?

**Comment by JustMaier** [comment]
Hey @gsales, Good question. I'm not really sure but I think the [SignalR group](https://github.com/SignalR/SignalR) might know.

**Comment by gsales** [comment]
In fact I went to the plugin and added a parameter to the more "hub.start" and sent `{jsonp: true}`, worked perfectly

**Comment by JustMaier** [comment]
Good to know. Thanks for the tip. I wonder if maybe we can expose those options so that you can do it without having to change the plugin
