### ISSUE TITLE
Change token if connection is established

### ISSUE THREAD

**Issue by ssczo** [JustMaier/angular-signalr-hub#27]
Is there a way to change query params on runtime? Should I close all connection and start new?

   queryParams:{
            'token': 'exampletoken'
        },

**Comment by JustMaier** [comment]
Hey @ssczo I'm actually not sure on this. It might be a question that could be better answered by the [signalr](https://github.com/SignalR/SignalR) team.

**Comment by ssczo** [comment]
I need to changed the bearer token in query string. My actual running solution is to close the connection --> change parms --> start new connection. This works perfekt!

**Comment by JustMaier** [comment]
Glad to hear that works as expected.
