### ISSUE TITLE
Confusing versioning

### ISSUE THREAD

**Issue by pascalberger** [JustMaier/angular-signalr-hub#29]
You recently released version [1.3.1](https://github.com/JustMaier/angular-signalr-hub/releases/tag/v1.3.1) on GitHub, but the [NuGet Packages](http://www.nuget.org/packages/AngularJs.SignalR.Hub/) are already at Version 1.3.3, but still contain version 1.3.0 of the script. 

It would be nice if you could have version numbering of in sync between GitHub releases and NuGet Packages and NuGet Packages always up to date.

**Comment by JustMaier** [comment]
@pascalberger Thanks for the heads up. With the last few commits being pull requests I had forgotten to update bower and nuget. All the version should be the same now, sorry for the confusion.
