### ISSUE TITLE
Should I used the Hub.connect().done on each server call

### ISSUE THREAD

**Issue by yehiasalam** [JustMaier/angular-signalr-hub#37]
Hello,

Thanks for the great plugin, great job. I came across this piece of code and I was trying to make sure i'm using it right. 

First I'm creating a Hub object
```javascript
			    var hub = new Hub('carbonSignalHub', {
			        rootPath: '/signalr',
			        methods: ['stepCreated', 'stepUpdated']
			    });
```

Now I want to call a message on the server, so I
```javascript
			        hub.connect().done(function () {
			            hub.stepCreated(JSON.stringify(step_loading));
			        }); 
```

But what if i want to call another function, how do I keep track that the connection is established, do I create another _hub.connect().done(.._ call as before or should I be keeping track of the connection status?

**Comment by DeBiese** [comment]
Hi. You should not call hub.connect() yourself. That's handled already. You just have to wait for the hub object you create to be ready for usage.

When you do var hub = new Hub(...); the connection will be made. Just handle hub.promise.done() in your code. (e.g. : set a ready flag indicating that the hub is ready for use)

After that, you can just call: hub.stepCreated or hub.stepUpdated. No need to wrap them in hub.connect().done...
