### ISSUE TITLE
NuGet dependencies

### ISSUE THREAD

**Issue by DeBiese** [JustMaier/angular-signalr-hub#38]
While making a non .net project, I noticed that you made the NuGet package dependant on Microsoft.AspNet.SignalR.
While in fact, you have only need for Microsoft.AspNet.SignalR.JS . Just the JavaScript client side.

I think you should consider modifying that. It might reach more people that way.

**Comment by JustMaier** [comment]
Thanks for the heads up. I've modified the dependency in the NuGet package in the latest version bump.

Thanks for all of your contributions to this project Ruben.
