### ISSUE TITLE
please provide a change log

### ISSUE THREAD

**Issue by niemyjski** [JustMaier/angular-signalr-hub#40]
I'm always checking the releases and there never is a change log so I have to go through all the commits. This would be a huge help to your loyal fans :)

**Comment by JustMaier** [comment]
Sure thing. I'll put one together.

**Comment by niemyjski** [comment]
I'd just do it for feature releases :) as it's less work

**Comment by JustMaier** [comment]
Good thinking. I'll do it going forward.

**Comment by niemyjski** [comment]
New version with no change log :(
