### ISSUE TITLE
Autoreconnecting on failure

### ISSUE THREAD

**Issue by niemyjski** [JustMaier/angular-signalr-hub#41]
Is this supported out of the box? What is the default behavior?

**Comment by DeBiese** [comment]
The default signalr connection behavior is fully explained here: 
http://www.asp.net/signalr/overview/guide-to-the-api/handling-connection-lifetime-events

The angular-signalr-hub does not automatically reconnect after a disconnect. There is however the possibility to provide a function yourself which handles the disconnected event. If you look at the readme, you'll see an example of automatically reconnecting when the connection got disconnected with an error. You could provide any code you like there. (hubDisconnected: function(){<enter your code>})

**Comment by niemyjski** [comment]
I knew that signalr reconnected but it seems that sometimes it doesn't try to hard to reconnect. Thanks, I'll look into that method.
