### ISSUE TITLE
bearer token issue.

### ISSUE THREAD

**Issue by zardaloop** [JustMaier/angular-signalr-hub#43]
Hi Justin,
Quick question. I know browser's websocket client doesn't allow custom headers to be set. But I get error  that the url is too long when I try to pass my bearer token within the queryParams. Obviously because my token is actually really long. Any idea how I can solve this issue? 
Many thanks in advance.

**Comment by JustMaier** [comment]
Hm, could you add an authorize method on the server side and then send the token via signalr to that method?
