### ISSUE TITLE
stateChanged option doesn't seem to do anything.

### ISSUE THREAD

**Issue by tdietrich513** [JustMaier/angular-signalr-hub#47]
I'd like to add some event handlers for the state change events, but it doesn't seem to be working. 

      stateChanged: function(state){
                    switch (state.newState) {
                        case $.signalR.connectionState.connecting:
                            eventsHub.status = "Connecting";
                            $rootScope.$digest();
                            break;
                        case $.signalR.connectionState.connected:
                            eventsHub.status = "Connected";
                            $rootScope.$digest();
                            break;
                        case $.signalR.connectionState.reconnecting:
                            eventsHub.status = "Reconnecting";
                            $rootScope.$digest();
                            break;
                        case $.signalR.connectionState.disconnected:
                            eventsHub.status = "Disconnected";
                            $rootScope.$digest();
                            break;
                    }
                }

The state changed function never seems to be called.

**Comment by JustMaier** [comment]
@tdietrich513 Did you do it in the constructor like below:

```javascript
var hub = new Hub('employee', {
stateChanged: function()...
});
```

**Comment by tdietrich513** [comment]
Yes that's how I was doing it.
