### ISSUE TITLE
Cross - domain Hub?

### ISSUE THREAD

**Issue by andrea-spotsoftware** [JustMaier/angular-signalr-hub#51]
Is it possible to use this hub for cross-domain signalr?
I've tried with rootPath options (rootPath: 'http://localhost:50803') but looks like it's not working.

Thanks

**Comment by DeBiese** [comment]
It is possible.
You just have to make sure the site you try to connect to allows cross domain connections.

**Comment by getuliojr** [comment]
Anyone got this working and there is an example with Owin ?

**Comment by DeBiese** [comment]
I can't provide you with a full working sample.
But I can show you (part) of an owin startup class for a website which hosts a hub that is accessible cross-domain.

```javascript
public class Startup
    {
        public void Configuration(IAppBuilder app)
        {            
            // Branch the pipeline here for requests that start with "/signalr"
            app.Map("/signalr", map =>
            {
                // Setup the CORS middleware to run before SignalR.
                // By default this will allow all origins. You can 
                // configure the set of origins and/or http verbs by
                // providing a cors options with a different policy.
                map.UseCors(CorsOptions.AllowAll);
                var hubConfiguration = new HubConfiguration
                {
                    EnableDetailedErrors = true,
                    EnableJSONP = true,
                    EnableJavaScriptProxies = true
                };
                // Run the SignalR pipeline. We're not using MapSignalR
                // since this branch already runs under the "/signalr"
                // path.
                map.RunSignalR(hubConfiguration);
            });
        }
    }
```

Note that in the sample I use `map.UseCors(CorsOptions.AllowAll);` which is probably not what you want in a production environment, but is usefull for testing.

**Comment by JustMaier** [comment]
Thanks for the example @DeBiese. I've added a Wiki page with your code. Does this work for you @getuliojr?

**Comment by getuliojr** [comment]
I got this working but have gone to other direction. I have updated web.config directly. Here is my startup

`public class Startup
    {

        public void Configuration(IAppBuilder app)
        {
            HttpConfiguration config = new HttpConfiguration();
            AutoMapperConfig.RegisterMappings();
            AutofacConfig.Register(config, app);
            OauthConfig.Register(config, app);
            WebApiConfig.Register(config);
            app.MapSignalR();
            app.UseWebApi(config);            
        }

    }`

And here is my web.config modifications to work:

`<system.webServer>
    <httpProtocol>
      <customHeaders>
        <remove name="Access-Control-Allow-Origin" />
        <remove name="Access-Control-Allow-Headers" />
        <remove name="Access-Control-Allow-Methods" />
        <remove name="Access-Control-Allow-Credentials" />
        <add name="Access-Control-Allow-Origin" value="http://localhost:10000" />
        <add name="Access-Control-Allow-Headers" value="Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With, Origin, Accept, ConnectionId" />
        <add name="Access-Control-Allow-Methods" value="GET,HEAD,POST,DEBUG,PUT,DELETE" />
        <add name="Access-Control-Allow-Credentials" value="true" />
      </customHeaders>
    </httpProtocol>
</system.webServer>`

**Comment by sreekumarp** [comment]
@getuliojr this worked for me. No changes required in client, only with this change in Web.Config it worked.

**Comment by getuliojr** [comment]
Glad to know @sreekumarp !!!
