### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by AdamSantaniello** [JustMaier/angular-signalr-hub#53]
A typescript definition currently doesn't exist for this at the moment. I'm working on creating it, and I will eventually submit it to DefinitelyTyped so it can be used for those who are working with this Hub factory in a Typescript project.

Here's a link to my fork of DefinitelyTyped:
https://github.com/AdamSantaniello/DefinitelyTyped

**Comment by JustMaier** [comment]
Cool! I haven't used TypeScript myself, but I'm sure there will be lots of people grateful for this.

**Comment by sstorie** [comment]
Is there any examples on how to instantiate a hub using the Typescript definition? I'm still learning how to use TS effectively, so I don't understand how the `HubFactory` interface relates to the original javascript.

**Comment by DeBiese** [comment]
Maybe you can try the following:
```javascript
module signalR.Test {
	declare var Hub: ngSignalr.HubFactory;

	export class TestService {
		private signalrHub: ngSignalr.Hub = null;

		constructor() {
			this.signalrHub = new Hub('testHub', { rootPath: '', listeners: {}, methods: [] });
		}
	}
}
```

I haven't tried this myself yet, but it gives the following output in plain javascript:
```javascript
var signalR;
(function (signalR) {
    var Test;
    (function (Test) {
        var TestService = (function () {
            function TestService() {
                this.signalrHub = null;
                this.signalrHub = new Hub('testHub', { rootPath: '', listeners: {}, methods: [] });
            }
            return TestService;
        })();
        Test.TestService = TestService;
    })(Test = signalR.Test || (signalR.Test = {}));
})(signalR || (signalR = {}));
```

**Comment by sstorie** [comment]
@DeBiese Thank you. I was making a silly oversight and didn't realize the `Hub` object you instantiate was in fact the `ngSignalr.HubFactory` type. Once I realized that it made sense to me.

**Comment by AdamSantaniello** [comment]
Sorry for my delayed response, but I did want to add a little bit of clarification. `ngSignalr.HubFactory` is intended to be a strongly typed way of representing the constructor function that gets injected into your angular module. The hub object that gets instantiated is still of type `Hub`. 

I think the `HubFactory` was probably the underlying source of confusion. I understand it may be a bit of a stretch to call it a factory at all. At the time I honestly couldn't really think of a better name. `IHub` didn't make sense and `HubConstructor` also didn't quite seem right either.

**Comment by JustMaier** [comment]
Hey Adam, do you think it would be helpful to have an example of how to instantiate with typescript? I haven't used typescript myself, so I'm not sure if this is necessary or helpful. We could make a Wiki page for it.

**Comment by AdamSantaniello** [comment]
I think that's a great idea. I'd be more than happy to write one up in the near future.

**Comment by JustMaier** [comment]
Great, thanks Adam.

**Comment by sstorie** [comment]
@AdamSantaniello I don't know if this is considered orthogonal or not, but I still get confused on how to leverage d.ts files with libraries I'm including with webpack. The issue I run into is I want to write typescript code like this:

```javascript
import * as ngSignalr from "angular-signalr-hub";
```

...but what I run into is the modules declared in the definition file usually use some other name that doesn't match the npm package name. For example, the d.ts file declares a module like so:
```javascript
declare module ngSignalr {
    interface HubFactory {
        /**
         * Creates a new Hub connection
         */
        new(hubName: string, options: HubOptions) : Hub
    }
...
```

So in a case like this library I end up patching the typescript definition files so the module they export matches the npm package name so both typescript and webpack are happy.

If this is something that could be included in the example, especially if I'm doing something really stupid here, it might be helpful for others as well.

**Comment by rocco-scaramuzzi** [comment]
Hi Guys, if someone still need it, [here ](https://github.com/rocco-scaramuzzi/angular-typescript-signalr)  I created a simple ASP.NET solution which contains a typescript implementation of the SignalR wrapper. The code you would be interested it is inside real time-app/collaborationService.ts

I hope it helps.
Cheers, 
Rocco

**Comment by lemkepf** [comment]
And just for anyone else coming here wondering about this topic... [here](https://github.com/rocco-scaramuzzi/angular-typescript-signalr/blob/fa93372de21ef726b4ff50febd77be7521692d93/AngualrTypeScriptSignalrExample/realtime-app/collaborationsService.ts#L18) is how you instantiate a hub within typescript.
