### ISSUE TITLE
After reconnecting, the hub will not send data to the server

### ISSUE THREAD

**Issue by GaryWenneker** [JustMaier/angular-signalr-hub#61]
steps to reproduce:
1. - client connects to the signalr enpoint
2. - client successfully sends data and receives data from signalr
3. - kill the server
4. - the hub throws an error: Error: WebSocket closed.
5. - state changed: 2
6. - bring up the server
7. - hub goes in reconnecting mode
8. - state changed: 1 (yes we got a connection again!!!)

so far so good.

but when I try to run step 2, the call is made to the hub but not passed to the server.
Fiddler even doesn't show anyting there.

**Comment by DeBiese** [comment]
Can you provide a sample project with this behavior? I have tested this before without issue. You can check out the simple chat demo which reconnects and is able to send/receive after a reconnect...

**Comment by GaryWenneker** [comment]
I've set up a new project and I think it was related to an old signalR jQuery script. Issue gone.
