### ISSUE TITLE
Returned data from hub server method

### ISSUE THREAD

**Issue by binaryForm** [JustMaier/angular-signalr-hub#63]
I'm trying to read data returned from a hub method, but done function doesn't seem to run... Could you let me know how to read the returned data? Thank you.

*hub code*
public string serverMethod(string param)
{
   return "result";
}

*client code*
hub.serverMethod('param').done(function (result) {
   console.log('result', result);
});

**Comment by JustMaier** [comment]
Hey @binaryForm, in SIgnalR serverMethods don't return a value, instead, they send messages to clients through client listeners. So your code would look something a little more like:

##hub code
```c#
public void serverMethod(string param){
Clients.Caller.clientMethod('result');
}
```

##client code
```js
var  hub = new Hub('hub', {
    listeners: {
        'clientMethod': function(result){
            console.log('result', result);
        }
    },
    methods: ['serverMethod']
});

hub.serverMethod('param');
```

**Comment by binaryForm** [comment]
Thank you, I'll call a client method instead. I was reading the documentation at http://www.asp.net/signalr/overview/guide-to-the-api/hubs-api-guide-server#asyncmethods and thought I was able to obtain return values as,

server code
```c#
public IEnumerable<Stock> GetAllStocks()
{
    // Returns data from memory.
    return _stockTicker.GetAllStocks();
}
```

client code
```javascript
stockTickerHubProxy.server.getAllStocks().done(function (stocks) {
    $.each(stocks, function () {
        alert(this.Symbol + ' ' + this.Price);
    });
});
```

**Comment by JustMaier** [comment]
You're totally right. Guess I just haven't used it that way :)

I just tested out your use case and `done` seems to fire without any problems. If it's still giving you trouble, maybe you can post your actual code?

**Comment by binaryForm** [comment]
I'll test again and let you know, thank you.

**Comment by binaryForm** [comment]
It works fine, silly me, I was referencing a hub in another server whose code didn't contain the function I was calling!

Thank you for your time, I appreciate it.
Best regards

**Comment by JustMaier** [comment]
Haha. Glad to hear it's working ok :)
