### ISSUE TITLE
SignalR 404 error when trying to negotiate

### ISSUE THREAD

**Issue by lvasilev1** [JustMaier/angular-signalr-hub#76]
So I am very new to SignalR, in fact I've only been using it for a couple of days now. Anyway, I am getting the error below when my application first starts up:

![signalr_negotiate_error](https://cloud.githubusercontent.com/assets/16479217/15614878/d21132e2-2400-11e6-9201-03f743ded542.png)

The code for the application in question is located in two projects, a Web API and a Single Page Application (SPA). The first one has my backend code (C#) and the second one my client-side code (AngularJS). I think the problem might be due to the fact that the projects in question run on different ports. The Web API, where my SignalR hub lives, is on port 60161 and the SPA is on 60813. My hub is declared like so:

![signalr_code_1](https://cloud.githubusercontent.com/assets/16479217/15615024/891bed10-2401-11e6-975c-e977aa02f10e.png)

and then in my Startup.cs file for my Web API I initialize SignalR like this:

![signalr_code_2](https://cloud.githubusercontent.com/assets/16479217/15615055/b2d28cb8-2401-11e6-9fb1-760b4f5ea600.png)

For my client-side code I use an Angular SignalR API called angular-signalr-hub (Angular-signalr-hub). The client-side follows:

![signalr_code_3](https://cloud.githubusercontent.com/assets/16479217/15615072/d5b3fe10-2401-11e6-8aa0-b37308d50796.png)

I did some googling yesterday and one of the suggestions I came upon was to set the SignalR URL to the one of my Web API, which I did (the commented out line above). When I uncomment the line in question, that does seem to do something because if I now go tohttp://localhost:60161/signalr/hubs in my browser, it does show me the dynamically generated proxy file:

![signalr_dynamic_proxy_file](https://cloud.githubusercontent.com/assets/16479217/15615083/e543b03c-2401-11e6-9d08-86e42b235719.png)

and when I run my application I no longer get the error above, but now it doesn't seem to connect. It gets to the negotiate line and it stops there:

![signalr_log](https://cloud.githubusercontent.com/assets/16479217/15615096/f2bbc7ea-2401-11e6-86e0-17e810492dea.png)

I think it should look like this (this is from a SignalR tutorial I found):

![signalr_log1](https://cloud.githubusercontent.com/assets/16479217/15615099/fdca250a-2401-11e6-99e9-6aae799da467.png)

In addition, none of my listeners (declared in my Angular code above) get called, so something is still now working quite right. There should be more lines in the log to the effect that connection was successfully established, etc. What could be the problem here?

**Comment by lvasilev1** [comment]
Upon further debugging I found out the problem is most likely in the following code segment, in file jquery.signal-2.2.0.js:

![signalr_log2](https://cloud.githubusercontent.com/assets/16479217/15676132/bb21d7aa-270a-11e6-8db2-2d86385f8ccf.png)

![signalr_log3](https://cloud.githubusercontent.com/assets/16479217/15676137/bfd36570-270a-11e6-9eed-37cbc3d7a7f1.png)

As you can see, the **ProtocolVersion** and **clientProtocol** values are different (one is 1.4 and the other one is 1.5) and because of that program execution goes into the IF clause and connection is not established. Any idea why these values differ? I tested with a tutorial I downloaded from the Internet and the values there are both 1.5.

**Comment by lvasilev1** [comment]
I figured out what the problem was. My SignalR dependencies were out of date and because of that my client and server versions differed. All I had to do was update (via NuGet Package Manager) all SignalR dependencies to the latest version and now it works.

As a side note, SignalR was not very good at telling me what was wrong. In fact, no error message was displayed, unless of course there was some additional logging somewhere that had to be found or turned on, in addition to the logging I already had (turned on). Either way, it's either not logging certain errors or it makes it difficult to figure out how to turn on all logging. I had to go and debug the JQuery SignalR api to figure out what the problem was, which was a time consuming endeavour.

**Comment by JustMaier** [comment]
Hey @lvasilev1, glad to hear you were able to solve the problem. There's actually an option to enable the SignalR logging: `logging: true/false`. I'm not sure, but maybe that would have helped catch the problem.

**Comment by lvasilev1** [comment]
I did enable it, but it did not show me any errors for the issue in question.

**Comment by JustMaier** [comment]
Bummer. You might reach out to the guys over at [SignalR](https://github.com/SignalR/SignalR) to see if they can improve that.
