### ISSUE TITLE
Multiple Hubs OnConnected

### ISSUE THREAD

**Issue by fwhenin** [JustMaier/angular-signalr-hub#81]
Hi, I currently have 3 separate hubs for different parts of our website (angular, requirejs). Things work just fine if I make a different signalr connection for each hub, but we found an issue with IE/Chrome that prevents the website open on more than 2 tabs (in our case). so I've been working on having all 3 hubs share the same connection.

2 of them work just fine, and the OnConnected for both get called at the same time since they're both part of a directive that loads at the same time. 

now the 3rd hub... that one gets loaded and called on a specific page of the application. if you're going to the url of that page directly then all is good...the OnConnected function gets called too on the server side. BUT if you load the web app from a different page snf then go to the page that needs that third hub, the onconnected doesn't get called (since it should already be connected which is fine). but I can't call `Client.Caller.DoSomething()` from the server at all...the angular hub doesn't seem to be listening for anything...any ideas? let me know if I need to explain more please

**Comment by JustMaier** [comment]
Hey @fwhenin, are you sure this isn't a problem at a lower level? This might be a problem with signalR and not the wrapper unfortunately. You might reach out to that team with your question: [SignalR GitHub](https://github.com/SignalR/SignalR)

**Comment by fwhenin** [comment]
@JustMaier I'm not 100% sure. Actually what I ended up doing was move all the logic to one single signalr hub. we later found an issue where if you have multiple tabs open, Chrome limits it to 6 signalr connections, so I don't run into this issue any more under one signalr hub

**Comment by jalchr** [comment]
Hi,
I had the same issue with 2 hubs, OnConnected was never called for the second one and all client side functions where never triggered.

My "solution" was to switch back to a single hub.
I think this is an issue that needs review.

Thanks,
