### ISSUE TITLE
Reconnecting not caught by stateChanged listener

### ISSUE THREAD

**Issue by zehavibarak** [JustMaier/angular-signalr-hub#82]
Reconnecting using $.conneciton.hub.start() or stop() doesn't trigger stateChanged listener
Tried with $.hubConnection() too. no luck

Any advice?

**Comment by JustMaier** [comment]
Hey @zehavibarak did you ever find a solution for this?

**Comment by zehavibarak** [comment]
Wire the underlying SignalR function, like this:
$.connection.hub.stateChanged(function (state) {
    switch (state.newState) {
        case $.signalR.connectionState.connected:
            ...
            break;
        ...
    }
});
