### ISSUE TITLE
Windows Authentication

### ISSUE THREAD

**Issue by Onefox** [JustMaier/angular-signalr-hub#83]
I was wondering how its possible to use windows authentication for a Hub.

I would like to be able to denial every non authenticated user the connection via:
`GlobalHost.HubPipeline.RequireAuthentication();` 

On the server-side, in the normal signalr hub there is a option Credentials on the HubConnection that you can fill with the default credentials. Here is some background infromation:
[http://www.c-sharpcorner.com/UploadFile/4b0136/different-ways-to-authenticate-and-authorize-signalr-hubs/](http://www.c-sharpcorner.com/UploadFile/4b0136/different-ways-to-authenticate-and-authorize-signalr-hubs/)

But the question is how to get that to work with this library so that i have the authenticated user in my Context.User.Identity for example.

**Comment by JustMaier** [comment]
Hey @Onefox this is probably a better question for the [SignalR team](https://github.com/SignalR/SignalR)
