### ISSUE TITLE
Getting connectionId from outside the Hub service

### ISSUE THREAD

**Issue by zalayeto** [JustMaier/angular-signalr-hub#86]
I need to send back to the server the connectionId of my client but I don't see how I can access to it once the connection has been created and my hub is connected.

Any ideas?

Thanks.

**Comment by shadow1349** [comment]
What I did was every time a client connected I set their connection id in a cookie so I can access it any time I want.

**Comment by zalayeto** [comment]
I've done something similar, just attach the connection Id when my connection is started on the client. But I think from the MvcApplication has to be a way of knowing the id of the current connection out of a HUB.

Cheers.
